### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by robbytriadi** [ictinnovations/ICTSchool#3]
I've succeeded install using ICTSchool01 but I found error while login using:
username: admin
password: 123456

Below is screenshot of the error:
![image](https://user-images.githubusercontent.com/49820621/81491074-e828a300-92b3-11ea-8e5a-7ba9ebb51d31.png)

Please help. Thank you

**Comment by fizaict** [comment]
Please update your ICTSchool installation and check again. The issue is fixed
